" -- Begin Pathogen-related settings
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
" -- End Pathogen-related settings
set nocompatible

" Make middle mouse paste without formatting
map <MouseMiddle> <Esc>"*p"

filetype plugin indent on
syntax on

set backspace=indent,eol,start

" Always work with logical lines, rather than screen lines
set linebreak
set textwidth=0

" Show partial commands entered in the last line
set showcmd

" Briefly show matching paren etc.
set showmatch

" Clever searching (ignores case unless a capital letter is present) and
" searches as I type
set ignorecase
set smartcase
set incsearch

" Write when switching to another file (not on tab change, of course)
set autowrite

" Old indentation settings, testing new ones
"set autoindent
"set tabstop=4
"set softtabstop=4
"set shiftwidth=4
"set smarttab 
"set expandtab 

" Emacs-like indentation settings
" (http://stackoverflow.com/questions/4085411/vim-indent-like-emacs)
set expandtab " will convert tabs to spaces
set autoindent " will keep indentation level from previous line
set shiftwidth=4 " will affect block indentation with >> and <<
set softtabstop=4 " sets the length of soft tab in spaces
set tabstop=8 " sets the width of tab character

" Set shiftwidth to 4 spaces for certain file types
au BufRead,BufNewFile *.py,*pyw,*.html,*.js set shiftwidth=4

" Makes powerline work (nicely)
set laststatus=2
let g:Powerline_stl_path_style = 'short'

" Don't suggest the following when looking for files to open
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.eps,.ps,.pdf

set term=xterm
if &term =~ "xterm"
  set t_Co=16
  set t_Sf=[3%dm
  set t_Sb=[4%dm
endif

" in normal mode: ^N twice toggles line numbers
nmap <C-N><C-N> :set invnumber <CR> 

" -- Begin simple arrow navigation
imap <buffer> <Up> <C-O>gk
imap <buffer> <Down> <C-O>gj

nmap <buffer> <Up> gk
nmap <buffer> <Down> gj

vmap <buffer> <Up> gk
vmap <buffer> <Down> gj
" -- End simple arrow navigation

" solarized theme
set background=dark
colorscheme solarized
