" vundle plugin management {{{
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
" tpope is incredible
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sleuth'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'mileszs/ack.vim'
Plugin 'chriskempson/base16-vim'
Plugin 'ervandew/supertab'
Plugin 'kien/ctrlp.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'bling/vim-airline'

Plugin 'itchyny/calendar.vim'

call vundle#end()
filetype plugin indent on
" }}}

" Obvious settings
syntax on

" The one true encoding!
set encoding=utf-8

" Typically, I want spell checking on
set spell

" Always work with logical lines, rather than screen lines
set linebreak
set textwidth=0

" Show partial commands entered in the last line
set showcmd

" Briefly show matching paren etc.
set showmatch

" Clever searching (ignores case unless a capital letter is present) and
" searches as I type
set ignorecase
set smartcase
set incsearch

" Write when switching to another file (not on tab change, of course)
set autowrite

" I only like particular folds, so only ones that I have asked for
set foldmethod=marker

" Glorious leader
let mapleader = "\\"

" Don't suggest the following when looking for files to open
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc,.eps,.ps,.pdf,.pyc

" color scheme {{{
set background=dark
colorscheme base16-twilight
" }}}

" Easier to hit keys for start/end of line
nnoremap H ^
nnoremap L $

" Persistent undo files should not clutter our directories
set undodir=~/.vim/undo

" Fugitive keys
nnoremap <Leader>gs :Gstatus<CR>
nnoremap <Leader>gc :Gcommit<CR>
nnoremap <Leader>gd :Gdiff<CR>

" PyLint settings {{{
let g:pymode_lint_write = 0
let g:pymode_syntax_highlight_self = 1
nnoremap <Leader>pl :PyLint<CR>
" }}}

" Jump to definition of a Python thing
nnoremap <Leader>pj :RopeGotoDefinition<CR>

" Change active split {{{
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
" }}}

" tab key configuration {{{
let g:ycm_key_list_select_completion=['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion=['<C-p>', '<Up>']

let g:UltiSnipsExpandTrigger="<Tab>"
let g:UltiSnipsJumpForwardTrigger="<Tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-Tab>"

let g:SuperTabDefaultCompletionType = '<C-n>'
" }}}

" ctrlp {{{
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
" }}}

" Calendar {{{
let g:calendar_google_calendar = 1
let g:calendar_google_task = 1
let g:calendar_week_number = 1
let g:calendar_first_day = "monday"
" }}}

if filereadable(glob("~/.vimrc.local")) 
	source ~/.vimrc.local
endif
